Microsoft.BeginDialog:
  widget: ActionCard
  header: Begin a new dialog
  body:
    widget: DialogReference
    dialog: ${action.dialog}
  footer:
    widget: SetResult
    value: ${action.resultProperty}
