Microsoft.BeginSkill:
  widget: ActionCard
  header:
    title: Connect to a skill
    icon: Library
    colors:
      theme: DarkBlue
      text: white
      icon: white
  body: ${concat(Gray30(Host")} ${coalesce(action.skillEndpoint, "?")}
  footer:
    widget: SetResult
    value: ${action.resultProperty}  
