Microsoft.Foreach:
  widget: 'ForeachWidget'
  nowrap: true
  loop:
    widget: 'ActionCard'
    header: 'Loop: For each item'
    body: 'Each value in {@itemsProperty || ?}'

Microsoft.ForeachPage:
  widget: 'ForeachWidget'
  nowrap: true
  loop:
    widget: 'ActionCard'
    header: 'Loop: For each page (multiple items)'
    body: 'Each page of {@pageSizeString || ?} in {@propString || ?}'
