Microsoft.ForeachPage:
  widget: ForeachWidget
  nowrap: true
  loop:
    widget: ActionCard
    header: Loop: For each page (multiple items)
    body: Each page of ${coalesce(action.pageSizeString, "?")} in ${coalesce(action.propString, "?")}
