Microsoft.SendActivity:
  widget: ActionCard
  header:
    title: Send a response
    icon: MessageBot
    colors:
      theme: '#EEEAF4'
      icon: '#5C2E91'
  body:
    widget: LgWidget
    value: ${action.activity}
  