Microsoft.SendActivity:
  widget: 'ActionCard'
  header:
    text: 'Send a response'
    icon: 'MessageBot'
    colors:
      theme: '#EEEAF4'
      icon: '#5C2E91'
  body:
    widget: 'LgWidget'
    value: '@activity'
  