Microsoft.SetProperties:
  widget: 'ActionCard'
  header: 'Set properties'
  body:
    widget: 'ListOverview'
    items: '@assignments.map(x => {{ property: x.property, value: x.value }})'
    itemWidget: 'PropertyAssignment'
