# TextInput
Microsoft.TextInput:
  widget: 'PromptWidget'
  nowrap: true
  botAsks:
    widget: 'ActionCard'
    header:
      title: 'Bot Asks (Text)'
      icon: 'MessageBot'
      colors:
        theme: '#EEEAF4'
        icon: '#5C2E91'
    body:
      widget: 'LG'
      value: '@prompt'
      placeholder: '<prompt>'
  userInput:
    widget: 'ActionCard'
    header:
      title: 'User Input (Text)'
      icon: 'User'
      menu: false
      colors:
        theme: '#lightblue'
        icon: '#azureblue'
    body: '@property ? {@property} <span style="color:grey">= Input(Text)</span> : '''
