name: Composer E2E test

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  Build-And-Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.DAILY_CI_AZURE_CREDENTIALS }}
        environment: 'AzureStack'

    - name: Build and Run Composer
      run: |
        yarn
        yarn build
        yarn start &
      working-directory: Composer

    - name: E2E test
      env:
          DAILY_CI_PUBLISH_FILE: ${{ secrets.DAILY_CI_PUBLISH_FILE }}
          DAILY_CI_DIRECTLINE_TOKEN: ${{ secrets.DAILY_CI_DIRECTLINE_TOKEN }}
      run: |
        sleep 30
        npm install
        npm run build
        npm test
      working-directory: Composer/dailyCI
