name: Composer E2E test

on:
  push:
    branches:
      - hond/testCI
# After this branch merged into main, would change the trigger event from 'push' to 'time schedule'
#  schedule:
# # Triggered once every day at 00:00
#    - cron:  '0 0 0 * * ?'

jobs:
  prepare-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run: git checkout hond/testCI

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.DAILY_CI_AZURE_CREDENTIALS }}
        environment: 'AzureStack'

    - name: Remove Resource
      uses: JesseTG/rm@v1.0.2
      with:
        path: Composer/packages/server/data.json

    - name: Copy Resource
      uses: canastro/copy-file-action@master
      with:
        source: "Composer/dailyCI/data.json"
        target: "Composer/packages/server/data.json"

    - name: Build and Run Composer
      run: |
        yarn
        yarn build
        yarn start &
      working-directory: Composer

    - name: E2E test
      env:
          DAILY_CI_PUBLISH_FILE: ${{ secrets.DAILY_CI_PUBLISH_FILE }}
          DAILY_CI_DIRECTLINE_TOKEN: ${{ secrets.DAILY_CI_DIRECTLINE_TOKEN }}
      run: |
        sleep 120
        npm install
        npm test
      working-directory: Composer/dailyCI
